#!/bin/bash

# ══════════════════════════════════════════════════════════════════════════════════ #
#  Script: generate_key.sh
#  Description: Generates an RSA key pair with 4096 bits.
#  Author: devinci-it
#  Date: $(date +"%Y-%m-%d")
#  Version: 1.0
# ══════════════════════════════════════════════════════════════════════════════════ #

# Variables
KEY_NAME="id_rsa_4096"  # Name for the key pair
KEY_DIR="$HOME/.ssh/keys/$KEY_NAME"  # Directory to store the key pair
PRIVATE_KEY="$KEY_DIR/$KEY_NAME"  # Path for the private key
PUBLIC_KEY="$KEY_DIR/$KEY_NAME.pub"  # Path for the public key

# Create a directory for the key pair
mkdir -p "$KEY_DIR"

# Generate the key pair
generate_key() {
    echo "Generating RSA key pair with 4096 bits..."
    if ssh-keygen -t rsa -b 4096 -f "$PRIVATE_KEY" -C "Generated by generate_key.sh" -q -N ""; then
        echo "RSA key pair generated successfully."
    else
        echo "Error: Failed to generate RSA key pair." >&2
        exit 1
    fi

    # Ensure the private key has the correct permissions
    chmod 600 "$PRIVATE_KEY"
    chmod 644 "$PUBLIC_KEY"
    echo "Key permissions set. Private key: 600, Public key: 644."
}

generate_key

# Output the result
echo "Private key: $PRIVATE_KEY"
echo "Public key: $PUBLIC_KEY"

